spring:
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    username: admin
    password: admin
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true